services:
  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis_prod_data:/data
      - ./server/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - pltgm-network

  server:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=${SERVER_PORT:-3001}
    build:
      context: server
      dockerfile: Dockerfile
      target: prod
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - pltgm-network

  client:
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: client/Dockerfile
      target: prod
    depends_on:
      - server
    networks:
      - pltgm-network

volumes:
  redis_prod_data:

networks:
  pltgm-network:
    driver: bridge
