services:
  server:
    image: ghcr.io/spamguy/pltgm-server:${TAG:-latest}
    environment:
      - SERVER_PORT=${SERVER_PORT:-3001}
      - DB_PATH=${DB_PATH:-/data/pltgm.db}
    build:
      context: server
      dockerfile: Dockerfile
      target: prod
    volumes:
      - sqlite_data:/data
    networks:
      - pltgm-network

  client:
    image: ghcr.io/spamguy/pltgm-client:${TAG:-latest}
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: client/Dockerfile
      target: prod
    depends_on:
      - server
    networks:
      - pltgm-network

volumes:
  sqlite_data:
    driver: local

networks:
  pltgm-network:
    driver: bridge
