CREATE TABLE IF NOT EXISTS games (
	id TEXT NOT NULL PRIMARY KEY,
	triplet TEXT NOT NULL,
	plate_text TEXT NOT NULL,
	origin TEXT NOT NULL,
	score INTEGER NOT NULL DEFAULT 0,
	started_at TEXT DEFAULT CURRENT_TIMESTAMP,
	ended_at TEXT
);

CREATE TABLE IF NOT EXISTS dictionary (
	word TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS guesses (
	game_id TEXT NOT NULL,
	guess TEXT NOT NULL,
	PRIMARY KEY (game_id, guess)
	FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE
);
